version: "3"
services:
  main-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "7777:7777"
    env_file:
      - .env
    depends_on:
      - postgres

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      default:
      monitoring:
        aliases:
          - prometheus
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      monitoring:
        aliases:
          - grafana

networks:
  monitoring:

volumes:
  postgres: